(()=>{'use strict';
const dialog=document.querySelector('.photo-dialog');let trigger;
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{trigger=b;dialog.querySelector('img').src=b.dataset.photo;dialog.querySelector('img').alt=b.querySelector('img').alt;dialog.querySelector('p').textContent=b.dataset.caption;dialog.showModal();}));
dialog.querySelector('.close-photo').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>trigger?.focus());
const steps=[{image:'images/spot-07.jpg',alt:'The vegetable selection at Iron Grill’s ingredient bar',copy:'Start with the vegetables, noodles and sauces you like. Choose your protein with the grill team.'},{image:'images/source-09.jpg',alt:'Vegetables and noodles cooking on Iron Grill’s hot grill',copy:'Your ingredients meet the hot grill, where the team cooks everything together in front of you.'},{image:'images/spot-09.jpg',alt:'A finished plate of vegetables, noodles and meat at Iron Grill',copy:'Your bowl becomes a hot meal. Sit down in the dining room or ask about taking it to go.'}];
const tabs=[...document.querySelectorAll('[data-step]')],panel=document.querySelector('#process-panel');
function select(n,focus=false){tabs.forEach((t,i)=>{t.classList.toggle('active',i===n);t.setAttribute('aria-selected',i===n?'true':'false');t.tabIndex=i===n?0:-1;});const s=steps[n],img=panel.querySelector('img');img.src=s.image;img.alt=s.alt;document.querySelector('#process-copy').textContent=s.copy;panel.setAttribute('aria-labelledby',tabs[n].id);if(focus)tabs[n].focus();}
tabs.forEach((t,n)=>{t.addEventListener('click',()=>select(n));t.addEventListener('keydown',e=>{let next=n;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(n+1)%3;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(n+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();select(next,true);});});
})();
